### ISSUE TITLE
Gtk dependancies avoidable

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar_python#16]
Hi,
I installed the package from source on the raspberry pi 4 for my boat.
I ran into a problem when I don't want to display the windows of the polarplot.
If I set debug to false, there is still a crach about my version of opencv gtk-less.

Would it be nice for embedded computer without gui to remove any call to windows display ?

I remove in node.py `cv2.destroyAllWindows()` as temporary patch for my case

**Comment by Hameck** [comment]
Hi Thomas,

We will try to take a look at this problem ASAP, thanks for reporting it.

Best regards,
Henrique

Em ter, 7 de jan de 2020 09:26, tomlogan501 <notifications@github.com>
escreveu:
