### ISSUE TITLE
Serial open when echoing data topic

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar_python#18]
**Describe the bug**
When I try to echoing the topic `/ping360_node/sonar/data ` on a remote computer, it tries to open the serial communication on this remote computer

**To Reproduce**
1. Launch the exemple launcher on the embedded computer
2. Rostopic on a remote computer the topic `/ping360_node/sonar/data `
3. See error `Opening /dev/ttyUSB0 at 115200 bps
Failed to open the given serial port
('\t', SerialException(2, "could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'"))
`

**Expected behavior**
Just display this topic

**Desktop (please complete the following information):**
 - ROS: kinetic on embedded computer, melodic on distant groundstation
 - Python: python2.7 and 3
 - Version: 1.2

**Comment by Hameck** [comment]
@tomlogan501 Thanks for reporting the error
